[[cable_channel]]
name = 's'
source_command = 'fd -t f -u . C:\'
preview_command = 'bat -n --color=always {0}'

[[cable_channel]]
name = 'c'
source_command = 'fd -t d -u . C:\'
preview_command = 'pwsh -NoProfile -Command Get-ChildItem -Force -LiteralPath "{0}"'

[[cable_channel]]
name = 'd'
source_command = 'fd -t d . D:\'
preview_command = 'pwsh -NoProfile -Command Get-ChildItem -Force -LiteralPath "{0}"'

[[cable_channel]]
name = 'u'
source_command = 'fd -t d . %USERPROFILE%\.config'
preview_command = 'pwsh -NoProfile -Command Get-ChildItem -Force -LiteralPath "{0}"'
