[ui]
use_nerd_font_icons = true
ui_scale = 100
show_help_bar = false
input_bar_position = "bottom"
theme = "vscode"

[previewers.file]
theme = "Visual Studio Dark+"

[keybindings.Channel]
quit = "esc"
select_next_entry = "down"
select_prev_entry = "up"
select_next_page = "pagedown"
select_prev_page = "pageup"
scroll_preview_half_page_down = "ctrl-d"
scroll_preview_half_page_up = "ctrl-u"
select_entry = "enter"
copy_entry_to_clipboard = "ctrl-y"
toggle_remote_control = "ctrl-r"
toggle_send_to_channel = "ctrl-s"
toggle_help = "ctrl-g"

[keybindings.RemoteControl]
quit = "esc"
select_next_entry = "down"
select_prev_entry = "up"
select_next_page = "pagedown"
select_prev_page = "pageup"
select_entry = "enter"
toggle_remote_control = "ctrl-r"
toggle_help = "ctrl-g"

[keybindings.SendToChannel]
quit = "esc"
select_next_entry = "down"
select_prev_entry = "up"
select_next_page = "pagedown"
select_prev_page = "pageup"
select_entry = "enter"
toggle_send_to_channel = "ctrl-s"
toggle_help = "ctrl-g"
