scheme = "vscode"
status_column_separator = " ▎ "
line_colors = {"#DEDEDE", "#BDBDBD", "#9C9C9C", "#7B7B7B", "#5A5A5A"}
highlights = {
  "Normal guibg=NONE guifg=NONE",
  "NormalFloat guibg=NONE guifg=NONE",
  "LineNr guibg=BG",
  "CursorLineNr guibg=BG",
  "SignColumn guibg=BG",
  "VertSplit guibg=BG",
  "Directory guibg=BG",
  "Question guibg=BG",
  "CocInlayHint guibg=BG",
  "Conceal guibg=BG",
  "FoldColumn guibg=BG",
  "Error guibg=BG",
  "ErrorMsg guibg=BG",
  "WarningMsg guibg=BG",
  "MoreMsg guibg=BG",
  "ModeMsg guibg=BG",
  "SpecialChar guibg=BG guifg=#D7BA7D",
  "Todo guibg=BG guifg=#0A7ACA",
  "DiagnosticWarn guibg=BG guifg=#FFE88B",
  "DiagnosticInfo guibg=BG guifg=#0A7ACA",
  "DiagnosticHint guibg=BG guifg=#0A7ACA",
  "DiagnosticUnderlineError gui=UNDERLINE guifg=#F44747",
  "DiagnosticUnderlineWarn gui=UNDERLINE guifg=#FFE88B",
  "DiagnosticUnderlineInfo gui=UNDERLINE guifg=#0A7ACA",
  "DiagnosticUnderlineHint gui=UNDERLINE guifg=#0A7ACA",
  "DiffAdd guibg=BG guifg=#4B5632",
  "DiffChange guibg=BG guifg=#646464",
  "DiffDelete guibg=BG guifg=#6F1313",
  "NeogitDiffAdd guibg=BG",
  "NeogitDiffAddHighlight guibg=BG",
  "NeogitDiffContext guibg=BG",
  "NeogitDiffContextHighlight guibg=BG",
  "NeogitDiffDelete guibg=BG",
  "NeogitDiffDeleteHighlight guibg=BG",
  "NeogitDiffHeader guibg=BG guifg=#C586C0",
  "NeogitDiffHeaderHighlight guibg=BG guifg=#C586C0",
  "NeogitHunkHeader guibg=BG",
  "NeogitHunkHeaderHighlight guibg=BG"
}
color_util.initialize_colors(scheme, highlights)
api.nvim_create_autocmd({"BufEnter", "WinEnter"},
                        {callback = function() color_util.line_number_handler(status_column_separator, line_colors) end})
