Color_util.initialize_colors("vscode", {
	"Normal guibg=none guifg=none",
	"NormalFloat guibg=none guifg=none",
	"TabLineSel guibg=bg",
	"Pmenu guibg=bg",
	"CmpItemAbbrDeprecated guibg=bg guifg=#444444",
	"LineNr guibg=bg",
	"CursorLineNr guibg=bg",
	"SignColumn guibg=bg",
	"VertSplit guibg=bg",
	"lualine_a_normal gui=bold guibg=#0a7aca guifg=#262626",
	"lualine_b_visual guibg=#373737 guifg=#ffaf00",
	"lualine_c_visual guibg=#262626 guifg=#ffffff",
	"Directory guibg=bg",
	"Question guibg=bg",
	"Conceal guibg=bg",
	"FoldColumn guibg=bg",
	"Folded guibg=bg guifg=#43698a",
	"Error guibg=bg",
	"ErrorMsg guibg=bg",
	"WarningMsg guibg=bg",
	"MoreMsg guibg=bg",
	"ModeMsg guibg=bg",
	"SpecialChar guibg=bg guifg=#d7ba7d",
	"Todo guibg=bg guifg=#0a7aca",
	"DiagnosticWarn guibg=bg guifg=#ffe88b",
	"DiagnosticInfo guibg=bg guifg=#0a7aca",
	"DiagnosticHint guibg=bg guifg=#0a7aca",
	"DiagnosticUnderlineError gui=underline guifg=#f44747",
	"DiagnosticUnderlineWarn gui=underline guifg=#ffe88b",
	"DiagnosticUnderlineInfo gui=underline guifg=#0a7aca",
	"DiagnosticUnderlineHint gui=underline guifg=#0a7aca",
	"DiagnosticDeprecated gui=underline guifg=#0a7aca",
	"DiagnosticUnnecessary gui=underline",
	"GitSignsAdd guibg=bg guifg=#4b5632",
	"GitSignsChange guibg=bg guifg=#646464",
	"GitSignsDelete guibg=bg guifg=#6f1313",
	"DiffAdd guibg=bg guifg=#4b5632",
	"DiffChange guibg=bg guifg=#646464",
	"DiffDelete guibg=bg guifg=#6f1313",
	"DiffText guibg=bg guifg=#6f1313",
	"NeogitDiffAdd guibg=bg",
	"NeogitDiffAddHighlight guibg=bg",
	"NeogitDiffContext guibg=bg",
	"NeogitDiffContextHighlight guibg=bg",
	"NeogitDiffDelete guibg=bg",
	"NeogitDiffDeleteHighlight guibg=bg",
	"NeogitDiffHeader guibg=bg guifg=#c586c0",
	"NeogitDiffHeaderHighlight guibg=bg guifg=#c586c0",
	"NeogitHunkHeader guibg=bg",
	"NeogitHunkHeaderHighlight guibg=bg",
	"NeogitFloatHeader guibg=bg",
	"NeogitFloatHeaderHighlight guibg=bg",
})
