local scheme = "vscode"
local highlights = {
	"Normal guibg=NONE guifg=NONE",
	"NormalFloat guibg=NONE guifg=NONE",
  "TabLineSel guibg=BG",
  "Pmenu guibg=BG",
  "CmpItemAbbrDeprecated guibg=BG guifg=#444444",
	"LineNr guibg=BG",
	"CursorLineNr guibg=BG",
	"SignColumn guibg=BG",
	"VertSplit guibg=BG",
	"lualine_a_normal gui=bold guibg=#0a7aca guifg=#262626",
	"lualine_b_visual guibg=#373737 guifg=#ffaf00",
	"lualine_c_visual guibg=#262626 guifg=#ffffff",
	"Directory guibg=BG",
	"Question guibg=BG",
	"Conceal guibg=BG",
	"FoldColumn guibg=BG",
	"Folded guibg=BG guifg=#43698a",
	"Error guibg=BG",
	"ErrorMsg guibg=BG",
	"WarningMsg guibg=BG",
	"MoreMsg guibg=BG",
	"ModeMsg guibg=BG",
	"SpecialChar guibg=BG guifg=#d7ba7d",
	"Todo guibg=BG guifg=#0a7aca",
	"DiagnosticWarn guibg=BG guifg=#ffe88b",
	"DiagnosticInfo guibg=BG guifg=#0a7aca",
	"DiagnosticHint guibg=BG guifg=#0a7aca",
	"DiagnosticUnderlineError gui=UNDERLINE guifg=#f44747",
	"DiagnosticUnderlineWarn gui=UNDERLINE guifg=#ffe88b",
	"DiagnosticUnderlineInfo gui=UNDERLINE guifg=#0a7aca",
	"DiagnosticUnderlineHint gui=UNDERLINE guifg=#0a7aca",
  "DiagnosticDeprecated gui=UNDERLINE guifg=#0a7aca",
  "GitSignsAdd guibg=BG guifg=#4b5632",
  "GitSignsChange guibg=BG guifg=#646464",
  "GitSignsDelete guibg=BG guifg=#6f1313",
	"DiffAdd guibg=BG guifg=#4b5632",
	"DiffChange guibg=BG guifg=#646464",
	"DiffDelete guibg=BG guifg=#6f1313",
	"DiffText guibg=BG guifg=#6f1313",
	"NeogitDiffAdd guibg=BG",
	"NeogitDiffAddHighlight guibg=BG",
	"NeogitDiffContext guibg=BG",
	"NeogitDiffContextHighlight guibg=BG",
	"NeogitDiffDelete guibg=BG",
	"NeogitDiffDeleteHighlight guibg=BG",
	"NeogitDiffHeader guibg=BG guifg=#c586c0",
	"NeogitDiffHeaderHighlight guibg=BG guifg=#c586c0",
	"NeogitHunkHeader guibg=BG",
	"NeogitHunkHeaderHighlight guibg=BG",
	"NeogitFloatHeader guibg=BG",
	"NeogitFloatHeaderHighlight guibg=BG",
}
color_util.initialize_colors(scheme, highlights)
