Format_util.setup({
  [{ "clang-format", "-i", "[|]" }] = {
    "c",
    "h",
    "cpp",
    "hpp",
    "inl",
    "objc",
    "objcpp",
    "cs",
    "cuda",
    "proto",
    "hlsl",
    "glsl",
    "vert",
    "frag",
    "comp",
    "geom",
    "tesc",
    "tese",
  },
  [{ "black", "[|]" }] = { "py", "python" },
  [{ "stylua", "[|]" }] = { "lua" },
  [{ "prettier", "[|]", "--write" }] = {
    "html",
    "js",
    "jsx",
    "javascript",
    "javascriptreact",
    "javascript.jsx",
    "typescript",
    "typescriptreact",
    "typescript.tsx",
    "css",
    "scss",
    "less",
    "json",
    "jsonc",
  },
})
vim.keymap.set("n", "<LEADER>kf", function() Format_util.format("%") end, { desc = "Format current buffer" })
vim.keymap.set("n", "<LEADER>kF", function() Format_util.format(".") end, { desc = "Format current directory" })
