Map("n", "s", "<Plug>(leap)")
Map("n", "S", "<Plug>(leap-from-window)")
Map({ "x", "o" }, "s", "<Plug>(leap-forward)")
Map({ "x", "o" }, "S", "<Plug>(leap-backward)")
Map({ "n", "x", "o" }, "<A-s>", function()
	require("leap-by-word").leap()
end)
