vim.pack.add({ "https://github.com/nvim-treesitter/nvim-treesitter" })
Treesitter_util.install(require("nvim-treesitter"), {
  vim = {},
  vimdoc = {},
  lua = {},
  diff = {},
  query = {},
  markdown = {},
  markdown_inline = {},
  hurl = {},
  http = {},
  html = {},
  javascript = {},
  css = {},
  python = {},
  sql = {},
  xml = {},
  json = {},
  yaml = {},
  toml = {},
  java = {},
  c_sharp = {},
  razor = {},
  c = {},
  cpp = {},
  hlsl = { "glsl", "vert", "frag", "comp", "geom", "tesc", "tese" },
  cmake = {},
  gitcommit = {},
  gitignore = {},
  regex = {},
  bash = { "sh", "dosbatch" },
  powershell = {},
})
vim.api.nvim_create_autocmd("PackChanged", { callback = function(event) Treesitter_util.changed(event) end })
