local trouble = require("trouble")
trouble.setup({ focus = true, preview = { scratch = false } })
Map("n", "gd", "<CMD>Trouble lsp_definitions<CR>")
Map("n", "gD", "<CMD>Trouble lsp_declarations<CR>")
Map("n", "gr", "<CMD>Trouble lsp_references<CR>")
Map("n", "gi", "<CMD>Trouble lsp_implementations<CR>")
Map("n", "gy", "<CMD>Trouble lsp_type_definitions<CR>")
Map("n", "gs", "<CMD>Trouble lsp_document_symbols<CR>")
Map("n", "<LEADER>td", "<CMD>Trouble diagnostics filter.buf=0<CR>")
Map("n", "<LEADER>tD", "<CMD>Trouble diagnostics<CR>")
Map("n", "<LEADER>tl", "<CMD>Trouble lsp<CR>")
Map("n", "<LEADER>tc", "<CMD>Trouble close<CR>")
Map("n", "<LEADER>e", "<CMD>lua vim.diagnostic.open_float({scope='cursor'})<CR>")
