require("trouble").setup({ focus = true, preview = { scratch = false } })
Map("n", "gd", "<CMD>Trouble lsp_definitions<CR>", { desc = "Go to definition(s)" })
Map("n", "gD", "<CMD>Trouble lsp_declarations<CR>", { desc = "Go to declaration(s)" })
Map("n", "gr", "<CMD>Trouble lsp_references<CR>", { desc = "Go to reference(s)" })
Map("n", "gi", "<CMD>Trouble lsp_implementations<CR>", { desc = "Go to implementation(s)" })
Map("n", "gy", "<CMD>Trouble lsp_type_definitions<CR>", { desc = "Go to type definition(s)" })
Map("n", "gs", "<CMD>Trouble lsp_document_symbols<CR>", { desc = "Go to document symbol(s)" })
Map("n", "<LEADER>td", "<CMD>Trouble diagnostics filter.buf=0<CR>", { desc = "View diagnostics for current buffer" })
Map("n", "<LEADER>tD", "<CMD>Trouble diagnostics<CR>", { desc = "View diagnostics for all buffers" })
Map("n", "<LEADER>tl", "<CMD>Trouble lsp<CR>", { desc = "View all lsp info for hovered symbol" })
Map("n", "<LEADER>tc", "<CMD>Trouble close<CR>", { desc = "Close the trouble window" })
