vim.pack.add({ { src = "https://github.com/Mofiqul/vscode.nvim", name = "vscode" } })
Color_util.initialize("vscode", {
  Normal = { guibg = "none", guifg = "none" },
  NormalFloat = { guibg = "none", guifg = "none" },
  LineNr = { guibg = "none" },
  CursorLineNr = { guibg = "none" },
  SignColumn = { guibg = "none" },
  VertSplit = { guibg = "none" },
  TabLineSel = { guibg = "none" },
  Pmenu = { guibg = "none" },
  FzfLuaBorder = { guibg = "none", guifg = "#5a5a5a" },
  Directory = { guibg = "none" },
  Question = { guibg = "none" },
  Conceal = { guibg = "none" },
  FoldColumn = { guibg = "none" },
  Folded = { guibg = "none", guifg = "#43698a" },
  Error = { guibg = "none", gui = "underline" },
  ErrorMsg = { guibg = "none" },
  WarningMsg = { guibg = "none" },
  MoreMsg = { guibg = "none" },
  ModeMsg = { guibg = "none" },
  SpecialChar = { guibg = "none", guifg = "#d7ba7d" },
  Todo = { guibg = "none", guifg = "#0a7aca" },
  CmpItemAbbrDeprecated = { guibg = "none", guifg = "#444444" },
  DiagnosticWarn = { guibg = "none", guifg = "#ffe88b" },
  DiagnosticInfo = { guibg = "none", guifg = "#0a7aca" },
  DiagnosticHint = { guibg = "none", guifg = "#0a7aca" },
  DiagnosticUnderlineError = { guifg = "#f44747", gui = "underline" },
  DiagnosticUnderlineWarn = { guifg = "#ffe88b", gui = "underline" },
  DiagnosticUnderlineInfo = { guifg = "#0a7aca", gui = "underline" },
  DiagnosticUnderlineHint = { guifg = "#0a7aca", gui = "underline" },
  DiagnosticDeprecated = { guifg = "#0a7aca", gui = "underline" },
  DiagnosticUnnecessary = { gui = "underline" },
  DapBreakpoint = { guibg = "none", guifg = "#0a7aca" },
  DapBreakpointCondition = { guibg = "none", guifg = "#ffe88b" },
  DapBreakpointRejected = { guibg = "none", guifg = "#f44747" },
  DapLogPoint = { guibg = "none", guifg = "#a0a0a0" },
  DapStopped = { guibg = "none", guifg = "#4c4c19" },
  GitSignsAdd = { guibg = "none", guifg = "#4b5632" },
  GitSignsChange = { guibg = "none", guifg = "#646464" },
  GitSignsDelete = { guibg = "none", guifg = "#6f1313" },
  DiffAdd = { guibg = "none", guifg = "#4b5632" },
  DiffChange = { guibg = "none", guifg = "#646464" },
  DiffDelete = { guibg = "none", guifg = "#6f1313" },
  DiffText = { guibg = "none", guifg = "#6f1313" },
  NeogitDiffAdd = { guibg = "none" },
  NeogitDiffAddHighlight = { guibg = "none" },
  NeogitDiffContext = { guibg = "none" },
  NeogitDiffContextHighlight = { guibg = "none" },
  NeogitDiffDelete = { guibg = "none" },
  NeogitDiffDeleteHighlight = { guibg = "none" },
  NeogitChangeNewFile = { guifg = "#4ec9b0" },
  NeogitChangeAdded = { guifg = "#4ec9b0" },
  NeogitChangeRenamed = { guifg = "#ffaf00" },
  NeogitChangeModified = { guifg = "#ffaf00" },
  NeogitUnpulledFrom = { guifg = "#0a7aca" },
  NeogitUnpushedTo = { guifg = "#0a7aca" },
  NeogitUnmergedInto = { guifg = "#0a7aca" },
  NeogitChangeUnmerged = { guifg = "#0a7aca" },
  NeogitDiffHeader = { guibg = "none", guifg = "#c586c0" },
  NeogitDiffHeaderHighlight = { guibg = "none", guifg = "#c586c0" },
  NeogitHunkHeader = { guibg = "none" },
  NeogitHunkHeaderHighlight = { guibg = "none" },
  NeogitFloatHeader = { guibg = "none" },
  NeogitFloatHeaderHighlight = { guibg = "none" },
  NeogitSectionHeader = { guifg = "#0a7aca" },
  CopilotSuggestion = { guibg = "none", guifg = "#888888" },
})
