Color_util.initialize_colors("vscode", {
  "Normal guibg=none guifg=none",
  "NormalFloat guibg=none guifg=none",
  "LineNr guibg=none",
  "CursorLineNr guibg=none",
  "SignColumn guibg=none",
  "VertSplit guibg=bg",
  "TabLineSel guibg=bg",
  "Pmenu guibg=bg",
  "FzfLuaBorder guibg=bg guifg=#5a5a5a",
  "Directory guibg=bg",
  "Question guibg=bg",
  "Conceal guibg=bg",
  "FoldColumn guibg=bg",
  "Folded guibg=bg guifg=#43698a",
  "Error guibg=bg",
  "ErrorMsg guibg=bg",
  "WarningMsg guibg=bg",
  "MoreMsg guibg=bg",
  "ModeMsg guibg=bg",
  "SpecialChar guibg=bg guifg=#d7ba7d",
  "Todo guibg=bg guifg=#0a7aca",
  "CmpItemAbbrDeprecated guibg=bg guifg=#444444",
  "DiagnosticWarn guibg=bg guifg=#ffe88b",
  "DiagnosticInfo guibg=bg guifg=#0a7aca",
  "DiagnosticHint guibg=bg guifg=#0a7aca",
  "DiagnosticUnderlineError guifg=#f44747 gui=underline",
  "DiagnosticUnderlineWarn guifg=#ffe88b gui=underline",
  "DiagnosticUnderlineInfo guifg=#0a7aca gui=underline",
  "DiagnosticUnderlineHint guifg=#0a7aca gui=underline",
  "DiagnosticDeprecated guifg=#0a7aca gui=underline",
  "DiagnosticUnnecessary gui=underline",
  "GitSignsAdd guibg=bg guifg=#4b5632",
  "GitSignsChange guibg=bg guifg=#646464",
  "GitSignsDelete guibg=bg guifg=#6f1313",
  "DiffAdd guibg=bg guifg=#4b5632",
  "DiffChange guibg=bg guifg=#646464",
  "DiffDelete guibg=bg guifg=#6f1313",
  "DiffText guibg=bg guifg=#6f1313",
  "NeogitDiffAdd guibg=bg",
  "NeogitDiffAddHighlight guibg=bg",
  "NeogitDiffContext guibg=bg",
  "NeogitDiffContextHighlight guibg=bg",
  "NeogitDiffDelete guibg=bg",
  "NeogitDiffDeleteHighlight guibg=bg",
  "NeogitChangeNewFile guifg=#4ec9b0",
  "NeogitChangeAdded guifg=#4ec9b0",
  "NeogitChangeRenamed guifg=#ffaf00",
  "NeogitChangeModified guifg=#ffaf00",
  "NeogitUnpulledFrom guifg=#0a7aca",
  "NeogitUnpushedTo guifg=#0a7aca",
  "NeogitUnmergedInto guifg=#0a7aca",
  "NeogitChangeUnmerged guifg=#0a7aca",
  "NeogitDiffHeader guibg=bg guifg=#c586c0",
  "NeogitDiffHeaderHighlight guibg=bg guifg=#c586c0",
  "NeogitHunkHeader guibg=bg",
  "NeogitHunkHeaderHighlight guibg=bg",
  "NeogitFloatHeader guibg=bg",
  "NeogitFloatHeaderHighlight guibg=bg",
  "NeogitSectionHeader guifg=#0a7aca",
  "CopilotSuggestion guibg=bg guifg=#888888",
})
