map("n", "s", "<Plug>(leap)")
map("n", "S", "<Plug>(leap-from-window)")
map({"x", "o"}, "s", "<Plug>(leap-forward)")
map({"x", "o"}, "S", "<Plug>(leap-backward)")
map({"n", "x", "o"}, "<A-s>", function() require("leap-by-word").leap() end)
