lazy_util.bootstrap()
map("n", "<LEADER>l", "<CMD>Lazy<CR>")
require("lazy").setup({
	{ "nvim-lua/plenary.nvim" },
	{ "stevearc/oil.nvim" },
	{ "nvim-telescope/telescope.nvim" },
	{ "nvim-telescope/telescope-fzf-native.nvim", build = "make" },
	{ "theprimeagen/harpoon", branch = "harpoon2" },
	{ "mbbill/undotree" },
	{ "gbprod/yanky.nvim" },
	{ "ggandor/leap.nvim" },
	{ "Sleepful/leap-by-word.nvim" },
	{ "kevinhwang91/nvim-bqf" },
	{ "itchyny/vim-qfedit" },
	{ "MunifTanjim/nui.nvim" },
	{ "nvim-tree/nvim-web-devicons" },
	{ "Mofiqul/vscode.nvim", name = "vscode" },
	{ "nvim-lualine/lualine.nvim" },
	{ "rcarriga/nvim-notify" },
	{ "folke/noice.nvim" },
	{ "nvim-treesitter/nvim-treesitter", build = ":TSUpdate" },
  { "williamboman/mason.nvim" },
  { "williamboman/mason-lspconfig.nvim" },
	{ "hrsh7th/cmp-nvim-lsp" },
	{ "hrsh7th/cmp-nvim-lsp-signature-help" },
	{ "hrsh7th/cmp-buffer" },
	{ "hrsh7th/cmp-path" },
  { "hrsh7th/nvim-cmp" },
  { "folke/trouble.nvim" },
  { "aznhe21/actions-preview.nvim" },
	{ "neovim/nvim-lspconfig" },
  { "lewis6991/gitsigns.nvim" },
  { "sindrets/diffview.nvim" },
	{ "NeogitOrg/neogit" },
	{ "supermaven-inc/supermaven-nvim" },
})
