Lazy_util.bootstrap()
Map("n", "<LEADER>l", "<CMD>Lazy<CR>", { desc = "Open Lazy" })
require("lazy").setup({
  { "nvim-lua/plenary.nvim" },
  { "stevearc/oil.nvim" },
  { "nvim-telescope/telescope.nvim" },
  { "nvim-telescope/telescope-fzf-native.nvim", build = "make" },
  { "nvim-telescope/telescope-ui-select.nvim" },
  { "mbbill/undotree" },
  { "gbprod/yanky.nvim" },
  { "kevinhwang91/nvim-bqf" },
  { "itchyny/vim-qfedit" },
  { "MunifTanjim/nui.nvim" },
  { "nvim-tree/nvim-web-devicons" },
  { "Mofiqul/vscode.nvim", name = "vscode" },
  { "nvim-lualine/lualine.nvim" },
  { "rcarriga/nvim-notify" },
  { "folke/noice.nvim" },
  { "nvim-treesitter/nvim-treesitter", build = ":TSUpdate" },
  { "williamboman/mason.nvim" },
  { "saghen/blink.cmp", version = "*" },
  { "folke/trouble.nvim" },
  { "lewis6991/gitsigns.nvim" },
  { "sindrets/diffview.nvim" },
  { "NeogitOrg/neogit" },
  { "supermaven-inc/supermaven-nvim" },
})
