Map("n", " ", "<NOP>")
Map("n", "<C-f>", "<NOP>")
Map("n", "<LEADER>w", "<CMD>w<CR>")
Map("n", "<LEADER>W", "<CMD>wa<CR>")
Map("n", "<LEADER>tw", "<CMD>set wrap!<CR>")
Map("n", "J", "mzJ`z")
Map("n", "gJ", "mzgJ`z")
Map("v", "J", ":m '>+1<CR>gv=gv")
Map("v", "K", ":m '<-2<CR>gv=gv")
Map({ "n", "v" }, "j", "gj")
Map({ "n", "v" }, "k", "gk")
Map("n", "<A-h>", "<C-w>h")
Map("n", "<A-j>", "<C-w>j")
Map("n", "<A-k>", "<C-w>k")
Map("n", "<A-l>", "<C-w>l")
Map("n", "<C-A-h>", "3<C-w><")
Map("n", "<C-A-j>", "3<C-w>-")
Map("n", "<C-A-k>", "3<C-w>+")
Map("n", "<C-A-l>", "3<C-w>>")
Map({ "n", "v" }, "<LEADER>y", [["+y]])
Map({ "n", "v" }, "<LEADER>Y", [["+Y]])
Map({ "x", "v" }, "<LEADER>p", [["_dP]])
Map({ "n", "v" }, "<LEADER>d", [["_d]])
Map({ "n", "v" }, "<LEADER>D", [["_D]])
Map({ "n", "v" }, "<LEADER>c", [["_c]])
Map({ "n", "v" }, "<LEADER>C", [["_C]])
Map({ "n", "v" }, "<LEADER>x", [["_x]])
Map({ "n", "v" }, "<LEADER>X", [["_X]])
Map("n", "<LEADER>s", ":%s/<C-r><C-w>/<C-r><C-w>/g<Left><Left>")
Map("n", "<C-s>", ":%s//g<Left><Left>")
Map("v", "<LEADER>s", '"hy:%s/<C-r>h/<C-r>h/g<Left><Left>')
Map("v", "<C-s>", ":s//g<Left><Left>")
Map("v", "<C-n>", ":normal ")
Map("n", "<LEADER>qg", function()
	Quickfix_util.grep_search()
end)
Map("n", "<LEADER>qw", function()
	Quickfix_util.grep_word()
end)
Map("n", "<LEADER>qW", function()
	Quickfix_util.grep_full_word()
end)
Map("v", "<LEADER>q", function()
	Quickfix_util.grep_selection()
end)
Map("n", "<LEADER>qo", "<CMD>copen<CR>")
Map("n", "<LEADER>qr", ":cdo s//g<Left><Left>")
Map("n", "<C-w>e", "<CMD>!explorer .<CR>")
Map("n", "<LEADER>v", "<CMD>!sh script/clean.sh<CR>")
Map("n", "<LEADER>b", '<CMD>!wezterm cli spawn --cwd . pwsh -NoExit -Command "sh script/build.sh"<CR>')
Map("n", "<LEADER>n", '<CMD>!wezterm cli spawn --cwd . pwsh -NoExit -Command "sh script/run.sh"<CR>')
Map("n", "<LEADER>m", '<CMD>!wezterm cli spawn --cwd . pwsh -Command "sh script/debug.sh"<CR>')
